In [29]:
import numpy as np

# 1.
## a+a = [ 40  60  80 100]
## a+b = [21 32 43 54]
## a+c = [21 31 41 51]
## a+d = [21 31 41 51]
## a+e = 無解

# 2.

In [30]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.zeros(3)

#no loop
print("NO_LOOP")
print((A+B)*(-A/2))

#loop
for i in range(0,3):
    C[i] = (A[i]+B[i])*(-A[i]/2) 
    
print("LOOP")
print(C)

NO_LOOP
[-1.5 -1.5 -1.5]
LOOP
[-1.5 -1.5 -1.5]


# 3

In [31]:
A = np.ones((1,6))
B = np.ones((6,1))

print(A * B)
print(A @ B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
