# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
sum()是python內建 np.sum(a) 跟 a.sum() 是陣列專有，差別在於定義在 np 或是 array 底下。

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
import numpy as np

In [3]:
A = np.random.random((5, 5))

A = (A-A.min())/ (A.max()-A.min())
print(A)

[[0.21403487 0.62364022 1.         0.02485891 0.55755782]
 [0.66188883 0.06990258 0.98414371 0.08231873 0.83105813]
 [0.45452102 0.18247106 0.22289955 0.06356032 0.44880257]
 [0.66818115 0.36468489 0.33870052 0.13014978 0.6225018 ]
 [0.73660241 0.08423222 0.66208915 0.73435118 0.        ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [4]:
Z = np.random.random(10)
Z[Z.argmax()] = -1
print(Z)

[ 0.4316735   0.67310293  0.06535104  0.03742786  0.15742769  0.29586191
  0.38141235 -1.          0.58833691  0.29334307]
